# Site settings
title: Portfolio for Mark Cloutier
description: Portfolio for Mark Cloutier
# baseurl: "/particle" # the subpath of your site, e.g. /blog

# User settings
username: Mark Cloutier
user_description: A Full Stack Software Engineer that loves a good challenge.
user_title: Full Stack Software Engineer
emailaddress: mark.l.cloutier@gmail.com
#twitter_username: lorem_ipsum
resume-url:  tbd
github-url:  https://github.com/mainstringargs
stackoverflow-url: https://stackoverflow.com/users/33863/mainstringargs?tab=profile
linkedin-url: https://www.linkedin.com/in/mark-cloutier-180a7910

baseBookshelfUrl: /bookshelf-data

#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-1749812-7"

exclude: ['package.json', 'src' , 'node_modules']
