# Site settings
title: Portfolio for Mark Cloutier
description: Portfolio for Mark Cloutier
# baseurl: "/particle" # the subpath of your site, e.g. /blog

# User settings
username: Mark Cloutier
user_description: Full Stack Software Engineer with a passion for implementing complex software solutions in intuitive, agile ways using my skills as a leader, technology enthusiast, and software developer. 
user_title: Full Stack Software Engineer
emailaddress: mark.l.cloutier@gmail.com
resume-url:  /assets/pdf/mainstringargs_github_resume.pdf
github-url:  https://github.com/mainstringargs
stackoverflow-url: https://stackoverflow.com/users/33863/mainstringargs?tab=profile
linkedin-url: https://www.linkedin.com/in/mark-cloutier-180a7910

baseBookshelfUrl: /bookshelf-data

#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-1749812-7"

exclude: ['package.json', 'src' , 'node_modules']
